spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/MotulRappiDB
    username: postgres
    password: Motu1f4N@2025?
    driver-class-name: org.postgresql.Driver
  profiles:
    active: dev