spring:
  datasource:
    url: jdbc:postgresql://${RDS_HOSTNAME:localhost}:${RDS_PORT:5433}/MotulRappiDB
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Motu1#R4ppI@2024}

logging:
  level:
    root: ERROR