eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  datasource:
    url: jdbc:postgresql://localhost:5433/MotulRappiDB
    username: postgres
    password: Motu1f4N@2025?
    driver-class-name: org.postgresql.Driver