spring:
  datasource:
    url: jdbc:postgresql://${RDS_HOSTNAME:localhost}:${RDS_PORT:5433}/MotulRappiDB
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Motu1f4N@2025?}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  profiles:
    active: dev